sudo: required
language: cpp
dist: focal

addons: &gcc10
  apt:
    packages:
      - g++-10
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'

addons: &clang12
  apt:
    packages:
      - clang-12
      - libc++-12-dev
      - libc++abi-12-dev
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main"
        key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"

matrix:
  include:
    # linux
    - env: GCC_VERSION=10 BUILD_TYPE=Debug CPP=20
      os: linux
      compiler: gcc
      addons: *gcc10

    - env: GCC_VERSION=10 BUILD_TYPE=Release CPP=20
      os: linux
      compiler: gcc
      addons: *gcc10

    - env: CLANG_VERSION=12 BUILD_TYPE=Debug CPP=20
      os: linux
      compiler: clang
      addons: *clang12

    - env: CLANG_VERSION=12 BUILD_TYPE=Release CPP=20 ASAN=On
      os: linux
      compiler: clang
      addons: *clang12

before_script:
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CXX="clang++" CC="clang"; fi
  - which $CXX
  - which $CC
  - $CXX --version
  - cmake --version

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p build && cd build
  - |
    cmake .. \
      --warn-uninitialized \
      -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
      -DCMAKE_CXX_STANDARD=$CPP
      
  - make VERBOSE=1 -j2
  - ctest -j2 --output-on-failure
  
